### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by brdjx** [layerhq/Layer-Parse-iOS-Example#7] opened 2015-04-16 20:00 UTC
Upon trying to log in, it never stops loading.
![screen shot 2015-04-16 at 2 59 36 pm](https://cloud.githubusercontent.com/assets/8014925/7190095/50b9361a-e449-11e4-8df4-cb93cb8d5e59.png)

**Comment by kmahal** [comment] 2015-04-21 00:57
HI @brdjx are there any error logs?  Please give us further detail.

**Comment by seyhunak** [comment] 2015-04-26 17:10
@kmahal  same here, followed all steps.

Here is the output;

![screen shot 2015-04-26 at 20 08 57](https://cloud.githubusercontent.com/assets/170820/7338292/1eee7c08-ec50-11e4-9887-6be48fd46e7f.png)

**Comment by kmahal** [comment] 2015-05-05 23:02
Feel free to open this back up if you still have this issue, but I'm closing it for now.

**Closed by kmahal** 2015-05-05 23:02 UTC

**Comment by nishantdongare** [comment] 2015-09-21 08:57
Hello @kmahal . I am facing the same issue. Here is my error log for same. But i am using ported program in swift. Please help me with this. Thanks

2015-09-21 14:22:05.852 Layer-Parse-iOS-Swift-Example[12387:67809] LayerKit client v0.15.0 loaded
Failed to connect to Layer: Error Domain=com.layer.LayerKit.Errors Code=6000 "The client is already in the process of establishing a connection." UserInfo=0x7fe6eb7257f0 {NSLocalizedDescription=The client is already in the process of establishing a connection.}
2015-09-21 14:22:38.700 Layer-Parse-iOS-Swift-Example[12387:67935] [Error]: function not found (Code: 141, Version: 1.7.5)
Parse Cloud function failed to be called to generate token with error: Optional(Error Domain=Parse Code=141 "function not found" UserInfo=0x7fe6eb6da420 {code=141, originalError=Error Domain=NSURLErrorDomain Code=-1011 "The operation couldn’t be completed. (NSURLErrorDomain error -1011.)", temporary=0, error=function not found, NSLocalizedDescription=function not found})

**Comment by DanielsCode** [comment] 2015-09-27 13:49
same here: 
Failed to connect to Layer: Error Domain=com.layer.LayerKit.Errors Code=6000
and after some time:
Failed to connect to Layer: Error Domain=SPDYSocketErrorDomain Code=7

**Comment by arnavcodebrew** [comment] 2015-09-28 04:40
hello nishant......arnav this side......r u able to connect and not able to
authenticate......

**Comment by DanielsCode** [comment] 2015-09-28 21:07
Hi,

no, the error occurs, if I try to connect to layer. Its weird, that I got this error only on a single iPhone (6s with iOS9). Attached you will find my login function ....  

  func loginLayer() {
        
        // Connect to Layer
        self.layerClient.connectWithCompletion { success, error in
            if (!success) {
                print("Failed to connect to Layer: \(error)")
            } else {
                let userID: String = PFUser.currentUser()!.objectId!
                // Once connected, authenticate user.
                // Check Authenticate step for authenticateLayerWithUserID source
                self.authenticateLayerWithUserID(userID, completion: { success, error in
                    if (!success) {
                        print("Failed Authenticating Layer Client with error:\(error)")
                    } else {
                        print("Authenticated")
                        self.presentConversationListViewController()
                    }
                })
            }
        }
    }

If I try another phone, I got these logs:
Failed to connect to Layer: Error Domain=com.layer.LayerKit.Errors Code=6000 "The client is already in the process of establishing a connection." UserInfo={NSLocalizedDescription=The client is already in the process of establishing a connection.}
Authenticated 

I am more then confused ....

**Comment by DanielsCode** [comment] 2015-09-28 21:34
I'll got these log: 

Failed to connect to Layer: Error Domain=SPDYSocketErrorDomain Code=7 "No endpoints available, unable to connect socket" UserInfo={NSLocalizedDescription=No endpoints available, unable to connect socket}

only on one specific device (iPhone 6S, iOS9).

**Comment by arnavcodebrew** [comment] 2015-09-29 05:22
hii guys........i  m using underneath functions and dey r working
good........


-(void)ApiCallingLayer{

    if([self isValidAppID]){



        //   self.application.applicationSupportsShakeToEdit = YES;



        // Initializes a LYRClient object



        NSURL *appID = [[NSURL alloc] initWithString:LQSLayerAppIDString];



        self.layerClient = [LYRClient clientWithAppID:appID];



        self.layerClient.autodownloadMIMETypes = [NSSet setWithObjects:
@"image/png", nil];



        [self.layerClient connectWithCompletion:^(BOOL success, NSError
*error) {



            if (!success) {



                NSLog(@"Failed to connect to Layer: %@", error);

            }



            else {



                [self authenticateLayerWithUserID: self.LQSCurrentUserID
completion:^(BOOL success, NSError *error) {



                    if (!success) {



                        NSLog(@"Failed Authenticating Layer Client with
error:%@", error);

                    }

                }];

            }

        }];



    }

}


#pragma mark - Layer Authentication Methods


- (void)authenticateLayerWithUserID:(NSString *)userID completion:(void (^)(
BOOL success, NSError * error))completion{



    if (self.layerClient.authenticatedUserID) {



        NSLog(@"Layer Authenticated as User %@", self.layerClient.
authenticatedUserID);

        AppDelegate *appD = (id)[[UIApplication sharedApplication] delegate
];

        appD.layerClient = self.layerClient;



        NSUserDefaults *defaults = [[NSUserDefaults alloc]init];

        [defaults setValue:@"1" forKey:@"layerSync"];

        self.layerClient.delegate = (id)self;



      //  [[NSNotificationCenter defaultCenter]
postNotificationName:@"fetchConversation"
object:nil];



        if (completion) completion(YES, nil);



        return;



    }





    // Authenticate with Layer

    /*

     * 1. Request an authentication Nonce from Layer

     */

    [self.layerClient requestAuthenticationNonceWithCompletion:^(NSString
*nonce, NSError *error) {



        if (!nonce) {



            if (completion) {



                completion(NO, error);



            }



            return;

        }



        /*

         * 2. Acquire identity Token from Layer Identity Service

         */

        [self requestIdentityTokenForUserID:userID appID:[self.layerClient.
appID absoluteString] nonce:nonce completion:^(NSString *identityToken,
NSError *error) {



            if (!identityToken) {



                if (completion) {

                    completion(NO, error);

                }



                return;

            }



            /*

             * 3. Submit identity token to Layer for validation

             */

            [self.layerClient authenticateWithIdentityToken:identityToken
completion:^(NSString *authenticatedUserID, NSError *error) {



                if (authenticatedUserID) {



                    if (completion) {



                        completion(YES, nil);

                    }



                    NSLog(@"Layer Authenticated as User: %@",
authenticatedUserID);

                    AppDelegate *appD = (id)[[UIApplication
sharedApplication] delegate];

                    appD.layerClient = self.layerClient;

                    NSUserDefaults *defaults = [[NSUserDefaults alloc]init];

                    [defaults setValue:@"1" forKey:@"layerSync"];



                    self.layerClient.delegate = (id)self;



                }

                else {



                    completion(NO, error);

                }

            }];

        }];

    }];

}


- (void)requestIdentityTokenForUserID:(NSString *)userID appID:(NSString
*)appID nonce:(NSString *)nonce completion:(void(^)(NSString
*identityToken, NSError *error))completion{



    NSParameterAssert(userID);

    NSParameterAssert(appID);

    NSParameterAssert(nonce);

    NSParameterAssert(completion);



    NSURL *identityTokenURL = [NSURL URLWithString:@"
https://layer-identity-provider.herokuapp.com/identity_tokens"];


    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL
:identityTokenURL];

    request.HTTPMethod = @"POST";

    [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"
];

    [request setValue:@"application/json" forHTTPHeaderField:@"Accept"];



    NSDictionary *parameters = @{ @"app_id": appID, @"user_id": userID,
@"nonce": nonce };

    NSData *requestBody = [NSJSONSerialization dataWithJSONObject:parameters
options:0 error:nil];

    request.HTTPBody = requestBody;



    NSURLSessionConfiguration *sessionConfiguration = [
NSURLSessionConfiguration ephemeralSessionConfiguration];

    NSURLSession *session = [NSURLSession sessionWithConfiguration
:sessionConfiguration];

    [[session dataTaskWithRequest:request completionHandler:^(NSData *data,
NSURLResponse *response, NSError *error) {



        if (error) {



            completion(nil, error);



            return;

        }



        // Deserialize the response

        NSDictionary *responseObject = [NSJSONSerialization
JSONObjectWithData:data options:0 error:nil];



        if(![responseObject valueForKey:@"error"]){



            NSString *identityToken = responseObject[@"identity_token"];

            completion(identityToken, nil);

        }



        else{



            NSString *domain = @"give domain";

            NSInteger code = [responseObject[@"status"] integerValue];

            NSDictionary *userInfo =

            @{

              NSLocalizedDescriptionKey: @"Layer Identity Provider Returned
an Error.",

              NSLocalizedRecoverySuggestionErrorKey: @"There may be a
problem with your APPID."

              };



            NSError *error = [[NSError alloc] initWithDomain:domain code:code
userInfo:userInfo];

            completion(nil, error);

        }



    }] resume];

}

**Comment by arnavcodebrew** [comment] 2015-09-29 05:25
and once u have connected and get authentication ....save it to the
appDelegate and use it further.........dont authenticate it again......

**Comment by NNeyzi** [comment] 2015-10-07 16:26
Hey guys, I had the same problem and was able to fix it following this stackoverflow thread:

http://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed-on-ios-9/30748166#30748166

As I understand it the problem is caused by a new iOS 9 feature called ATS (App Transport Security). Disabling it from the info.plist file is an easy temporary fix.

Here's a good article about ATS in detail:
http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

**Comment by jaysnanavati** [comment] 2015-10-18 13:06
@NNeyzi I wasent able to resolve this using the posts you mentioned.. even after setting NSAllowsArbitraryLoads to true

**Comment by stevenmunoz** [comment] 2015-10-22 20:27
I´m trying to test the swift version and i´m getting the same error, when try to sign up
Example[16873:1592328] LayerKit client v0.16.0 loaded
Failed to connect to Layer: Error Domain=com.layer.LayerKit.Errors Code=6000 "The client is already in the process of establishing a connection." UserInfo={NSLocalizedDescription=The client is already in the process of establishing a connection.}

**Comment by sibeliusseraphini** [comment] 2015-11-04 02:53
To use Parse, you should follow the instructions of this repo: https://github.com/layerhq/layer-parse-module

**Comment by tejans24** [comment] 2016-01-03 23:32
I'm seeing the same problem, what's the solution here?

**Comment by bluv** [comment] 2016-01-10 18:54
I'm having the same problem. Endless loading. Anyone?

**Comment by Daheahty** [comment] 2016-01-12 01:44
Same problem here, is this something to do with App Transport Security?

**Comment by Daheahty** [comment] 2016-01-16 21:51
Hi All,

I have exactly the same error on the swift port. Has anyone managed to find a fix to this error?

Thanks

Marc

**Comment by jorgeirun** [comment] 2016-01-29 22:29
Same here.. no news?

**Comment by sibeliusseraphini** [comment] 2016-01-29 22:42
Parse was shut down

**Comment by jorgeirun** [comment] 2016-01-29 22:44
AFAIK Parse will continue for almost a year.. also, people had this issue for weeks, didn't start yesterday..

**Comment by Leomax004** [comment] 2016-03-17 11:33
Finally able to solve this issue.
If you are using Ios-9,then you have to add some ATS exception in your plist manually from the below link:
https://support.layer.com/hc/en-us/articles/205034154-Are-there-any-known-issues-with-iOS-9-
just copy & paste into the plist.
If you are still getting the same error,then you have to Reset the Network settings of your Device
i:e:- Settings->General->Reset->Reset Network settings.
that's solve

**Comment by sara-shokry** [comment] 2016-04-07 23:12
i added the changes in plist and change network but still have same error iOS 9.3

**Comment by Leomax004** [comment] 2016-04-08 05:48
@sara-shokry did u reset the network setting of your device?

**Comment by rahulgarg12** [comment] 2016-07-27 19:03
I am still facing the same issue. I am working on Swift and not using Parse. I have added ATS exceptions too, still no luck. Has anyone fixed this error?

**Comment by Leomax004** [comment] 2016-07-27 19:04
Just reset network setting of your device
